WebBanHang/WebBanHang/Areas/Admin/Controllers/QuanLyDonHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;
using PagedList;
namespace WebBanHang.Areas.Admin.Controllers
{
    [Authorize(Roles = "Member")]

    public class QuanLyDonHangsController : Controller
    {
        DBBanHangEntities1 db = new DatabaseEntity().GetData();
        // GET: Admin/QuanLyDonHnangs
        public ActionResult ShowDonDatHang(int? MaDDH)
        {
            DonDatHang donhang = db.DonDatHangs.SingleOrDefault(p=>p.MaDDH==MaDDH);
            return View(donhang);
        }
        public ActionResult LuuDonHang(DonDatHang donHang)
        {
            DonDatHang  dh = db.DonDatHangs.Single(p=>p.MaDDH==donHang.MaDDH);
            dh.DaThanhToan = donHang.DaThanhToan;
            dh.DaHuy = donHang.DaHuy;

            if (dh.TrinhGiao==false && donHang.TrinhGiao==true)
            {
                dh.NgayGiao = DateTime.Now;
            }
            dh.TrinhGiao = donHang.TrinhGiao;
            db.SaveChanges();
            return RedirectToAction("DonHangHoanThanh");
        }
        int pageSize = 8;
        public  ActionResult DonHangHoanThanh(int? page)
        {
            List<DonDatHang> donDatHangs = db.DonDatHangs.Where(p=>p.DaThanhToan==true && p.TrinhGiao==true).OrderByDescending(p => p.NgayGiao).ToList();
            ViewBag.Title = "Đã hoàn thành .";
            ViewBag.isLink = "a";
            int pageNumber = (page ?? 1);
            return View(donDatHangs.ToPagedList(pageNumber,pageSize));
        }
        public ActionResult DonHangChưaThanhToans(int? page)
        {
            List<DonDatHang> donDatHangs = db.DonDatHangs.Where(p => p.DaThanhToan != true && p.TrinhGiao == true).OrderByDescending(p=>p.NgayGiao).ToList();
            ViewBag.Title = "Chưa thanh toán & Đã giao!";
            int pageNumber = (page ?? 1);
            ViewBag.isLink = "b";
            return View("DonHangHoanThanh",donDatHangs.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult DonHangChuaGiao(int? page)
        {
            List<DonDatHang> donDatHangs = db.DonDatHangs.Where(p => p.DaThanhToan == true && p.TrinhGiao != true).OrderByDescending(p => p.NgayDatHang).ToList();
            ViewBag.Title = "Đã Thanh toán & Chưa giáo .";
            ViewBag.isLink = "c";
            int pageNumber = (page ?? 1);
            return View("DonHangHoanThanh", donDatHangs.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult ChoDuyet(int? page)
        {
            List<DonDatHang> donDatHangs = db.DonDatHangs.Where(p => p.DaThanhToan != true && p.TrinhGiao != true).OrderByDescending(p => p.NgayDatHang).ToList();
            ViewBag.Title = "Chờ Duyệt";
            ViewBag.isLink = "d";
            int pageNumber = (page ?? 1);
            return View("DonHangHoanThanh", donDatHangs.ToPagedList(pageNumber, pageSize));
        }




    }
}

WebBanHang/WebBanHang/Areas/Admin/Views/QuanLyDonHangs/DonHangHoanThanh.cshtml
@using WebBanHang.Models;
@using PagedList.Mvc;
@model PagedList.IPagedList<DonDatHang>
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>Quản lý đơn đặt hàng</h2>
<hr />

<a class="btn btn-link" href="@Url.Action("DonHangChưaThanhToans")">Chưa thanh toán & Đã giao</a>
<a class="btn btn-link" href="@Url.Action("DonHangChuaGiao")">Chưa Giao & Đã thanh toán</a>
<a class="btn btn-link" href="@Url.Action("DonHangHoanThanh")">Đã hoàn thành</a>
<a class="btn btn-link" href="@Url.Action("ChoDuyet")">Chờ duyệt</a>
<hr />
<h3>@ViewBag.Title</h3>
<table class="table table-condensed">
    <thead>
        <tr>
            <th>Đơn hàng</th>
            <th>Mã khách hàng</th>
            <th>Họ tên</th>
            <th>Số điện thoại</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.MaDDH
                </td>
                <td>
                    @item.MaKH
                </td>
                <td>
                    @item.KhachHang.TenKH
                </td>
                <td>
                    @item.KhachHang.DienThoai
                </td>
                <td>
                    <a href="@Url.Action("ShowDonDatHang",new { MaDDH=item.MaDDH})" class="btn btn-link">Duyệt đơn hàng</a>
                </td>

            </tr>
        }
    </tbody>
</table>
@if (ViewBag.isLink == "a")
{
    @Html.PagedListPager(Model, page => Url.Action("DonHangHoanThanh", new { page = page }))
}
@if (ViewBag.isLink == "b")
{
    @Html.PagedListPager(Model, page => Url.Action("DonHangChưaThanhToans", new { page = page }))
}
@if (ViewBag.isLink == "c")
{
    @Html.PagedListPager(Model, page => Url.Action("DonHangChuaGiao", new { page = page }))
}
@if (ViewBag.isLink == "d")
{
    @Html.PagedListPager(Model, page => Url.Action("ChoDuyet", new { page = page }))
}

WebBanHang/WebBanHang/Areas/Admin/Views/QuanLyDonHangs/ShowDonDatHang.cshtml
@using WebBanHang.Models;
@model DonDatHang
@{
    ViewBag.Title = "ShowDonDatHang";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayoutPage.cshtml";
}

    <div class="Content">

        <h2>Khách Hàng : @Model.KhachHang.TenKH</h2>
        <h4>Địa chỉ : @Model.KhachHang.DiaChi</h4>
        <h4>Số điện thoại : @Model.KhachHang.DienThoai</h4>
        <h4>Email : @Model.KhachHang.Email</h4>
        <h4>Ngày đặt : @Model.NgayDatHang</h4>
        <hr />
        <h2>Đơn hàng</h2>
        @using (Html.BeginForm("LuuDonHang","QuanLyDonHangs",FormMethod.Post,new { @class="formDonHang"}))
        {
            <div class="form-group">
                <label class="control-label col-md-2">Đơn hàng</label>
                <div class="col-md-10">
                    <input class="form-control" name="MaDDH" value="@Model.MaDDH" readonly/>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Thanh toán</label>
                <div class="col-md-10">
                    <select name="DaThanhToan" class="form-control">
                        <option  @(Model.DaThanhToan==true?"selected":"") value="true">Đã thanh toán</option>
                        <option @(Model.DaThanhToan!=true?"selected":"") value="false">Chưa thanh toán</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Trình giao hàng</label>
                <div class="col-md-10">
                    <select name="TrinhGiao" class="form-control">
                        <option @(Model.TrinhGiao==true?"selected":"") value="true">Đã giao</option>
                        <option @(Model.TrinhGiao!=true?"selected":"") value="false">Chưa giao</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Hiệu lực</label>
                <div class="col-md-10">
                    <select name="DaHuy" class="form-control">
                        <option @(Model.DaHuy!=false?"selected":"") value="false">Chưa hủy</option>
                        <option @(Model.DaHuy==false?"selected":"") value="true">Đã hủy</option>
                    </select>
                </div>
            </div>
        }
        <hr />
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>Sản phẩm</th>
                    <th>Hình ảnh</th>
                    <th>Giá</th>
                    <th>Số lượng</th>
                    <th>Thành tiền</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int TongSoSP = 0;
                    var tongTien = 0;
                    decimal ThanhTien;
                }
                @foreach (var item in Model.ChiTietDonDatHangs)
                {

                    TongSoSP += item.SoLuong.Value;
                    ThanhTien = (item.SanPham.DonGia * item.SoLuong).Value;
                    tongTien += Int32.Parse(ThanhTien.ToString());
                    <tr>
                        <td>
                            @item.MaSP
                        </td>
                        <td>
                            <img width="80px" height="80px" src="@item.SanPham.HinhAnh" />
                        </td>
                        <td>
                            @String.Format("{0:#,##}", item.SanPham.DonGia) VND
                        </td>
                        <td>
                            @item.SoLuong
                        </td>
                        <td>@String.Format("{0:#,##}", item.SanPham.DonGia * item.SoLuong) VND</td>
                    </tr>
                }
                <tr>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                        Tống số lượng : @TongSoSP sản phẩm
                    </td>
                    <td> Tổng tiền :  @String.Format("{0:#,##}", tongTien) VND</td>
                </tr>
            </tbody>
        </table>
    </div>
<span class="btn btn-primary " id="btnInDonHang">In đơn hàng</span>
<span class="btn btn-primary" id="btnLuuDon">Lưu đơn hàng</span>



<script>
    $("#btnLuuDon").click(function () {
        $(".formDonHang").submit();
    });
    $("#btnInDonHang").click(function () {
        var Content = $(".Content").html();
        PrintPanel(Content);
    });
    function PrintPanel(Content) {
        var printWindow = window.open('', '', 'height=400,width=800');
        printWindow.document.write('<html><head><title>DIV Contents</title>');
        printWindow.document.write('</head><body >');
        printWindow.document.write(Content);
        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();
        return false;
    }

</script>