WebBanHang/WebBanHang/Areas/Clience/Models/ItemCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebBanHang.Models;
namespace WebBanHang.Areas.Clience.Models
{
    public class ItemCartViewModel
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public decimal ThanhTien { get; set; }
        public string HinhAnh { get; set; }
        DBBanHangEntities1 DB = new DatabaseEntity().GetData();
        public ItemCartViewModel(int MaSP , int sl)
        {
            this.MaSP = MaSP;
            SanPham sanPham = DB.SanPhams.Single(p=>p.MaSP==MaSP);
            this.TenSP = sanPham.TenSP;
            this.SoLuong = sl;
            this.DonGia = sanPham.DonGia.Value;
            this.ThanhTien = SoLuong * DonGia;
            this.HinhAnh = sanPham.HinhAnh;
        }
        public ItemCartViewModel(int MaSP)
        {
            this.MaSP = MaSP;
            SanPham sanPham = DB.SanPhams.Single(p => p.MaSP == MaSP);
            this.TenSP = sanPham.TenSP;
            this.SoLuong = 1;
            this.DonGia = sanPham.DonGia.Value;
            this.ThanhTien = SoLuong * DonGia;
            this.HinhAnh = sanPham.HinhAnh;
        }
        public ItemCartViewModel()
        {
        }
    }
}

WebBanHang/WebBanHang/Areas/Clience/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Areas.Clience.Models;
using WebBanHang.Models;

namespace WebBanHang.Areas.Clience.Controllers
{
    public class CartController : Controller
    {
        DBBanHangEntities1 DB = new DatabaseEntity().GetData();
        public List<ItemCartViewModel> GetCart()
        {
            List<ItemCartViewModel> itemCarts = Session["Cart"] as List<ItemCartViewModel>;
            if (itemCarts == null)
            {
                itemCarts = new List<ItemCartViewModel>();
                Session["Cart"] = itemCarts;
            }
            return itemCarts;
        }
        public ActionResult AddToCart(int? MaSP , string strUrl)
        {
            SanPham findSP = DB.SanPhams.SingleOrDefault(p=>p.MaSP==MaSP);
            if (findSP == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<ItemCartViewModel> itemCarts = GetCart();
            ItemCartViewModel findItemCart = itemCarts.SingleOrDefault(p=>p.MaSP==MaSP);
            
            if (findItemCart != null)
            {

                    if (findSP.SoLuongTon <= findItemCart.SoLuong)
                    {
                        return Content("Sản phẩm tồn Không đủ !");
                    }
                findItemCart.SoLuong++;
                findItemCart.ThanhTien = findItemCart.DonGia * findItemCart.SoLuong;
                return Redirect(strUrl);
            }

                ItemCartViewModel itemCart = new ItemCartViewModel(MaSP.Value);
                itemCarts.Add(itemCart);
               return Redirect(strUrl);

        }
        public int TongSoLuong()
        {
            List<ItemCartViewModel> itemCarts = Session["Cart"] as List<ItemCartViewModel>;
            if (itemCarts == null)
            {
                return 0;
            }
            return itemCarts.Sum(p=>p.SoLuong);

        }
        public decimal TongTien()
        {
            List<ItemCartViewModel> itemCarts = Session["Cart"] as List<ItemCartViewModel>;
            if (itemCarts == null)
            {
                return 0;
            }
            return itemCarts.Sum(p => p.ThanhTien);
        }
        public bool IsNumber(string pValue)
        {
            foreach (Char c in pValue)
            {
                if (!Char.IsDigit(c))
                    return false;
            }
            return true;
        }
        // GET: Clience/Cart
        public ActionResult ShowCart()
        {
            List<ItemCartViewModel> itemCarts = Session["Cart"] as List<ItemCartViewModel>;
            ViewBag.SoLuongs = TongSoLuong();
            ViewBag.TongTien = TongTien();

            return View(itemCarts);
        }
        public ActionResult CartPartial()
        {
            ViewBag.SoLuongs = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return View();
        }
        public ActionResult EditCart(int? MaSP)
        {
            SanPham findSP = DB.SanPhams.SingleOrDefault(p => p.MaSP == MaSP);
            if (findSP == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            if (Session["Cart"] == null )
            {
                return RedirectToAction("ShowCart");
            }
            List<ItemCartViewModel> itemCarts = Session["Cart"] as List<ItemCartViewModel>;
            ItemCartViewModel itemCart = itemCarts.SingleOrDefault(p => p.MaSP == MaSP);
            if (itemCart == null)
            {
                return RedirectToAction("ShowCart");
            }
            ViewBag.Cart = itemCarts;
            return View(itemCart);
        }
        public ActionResult UpdateCart(ItemCartViewModel itemCart)
        {
            if (Session["Cart"] == null)
            {
                return RedirectToAction("ShowCart");
            }

            SanPham sanPham = DB.SanPhams.SingleOrDefault(p => p.MaSP == itemCart.MaSP);
            if (sanPham==null)
            {
                return RedirectToAction("ShowCart");
            }
            if (itemCart.SoLuong < 1 || !IsNumber(itemCart.SoLuong.ToString()))
            {
                return RedirectToAction("DeleteItemCart", new { MaSP = itemCart.MaSP });
            }
            if (sanPham.SoLuongTon < itemCart.SoLuong)
            {
                return Content("Số lượng sản phẩm tồn không đủ !");
            }

            List<ItemCartViewModel> itemCarts = GetCart();

            ItemCartViewModel updateItemCart = itemCarts.Find(p=>p.MaSP==itemCart.MaSP);
            updateItemCart.SoLuong = itemCart.SoLuong;
            updateItemCart.ThanhTien = itemCart.SoLuong * updateItemCart.DonGia;
            return RedirectToAction("ShowCart");
        }
        public ActionResult DeleteItemCart(int? MaSP)
        {
            if (!MaSP.HasValue)
            {
                return RedirectToAction("ShowCart");
            }
            if (Session["Cart"] == null)
            {
                return RedirectToAction("ShowCart");
            }

            SanPham sanPham = DB.SanPhams.SingleOrDefault(p => p.MaSP == MaSP);
            if (sanPham == null)
            {
                return RedirectToAction("ShowCart");
            }
            List<ItemCartViewModel> itemCarts = GetCart();

            ItemCartViewModel updateItemCart = itemCarts.Find(p => p.MaSP == MaSP);
            if (updateItemCart == null)
            {
                return RedirectToAction("ShowCart");
            }
            itemCarts.Remove(updateItemCart);
            return RedirectToAction("ShowCart");
        }
        public KhachHang IsKhachHang(KhachHang khachHang)
        {
            KhachHang isKhach = DB.KhachHangs.SingleOrDefault(p=>p.DienThoai==khachHang.DienThoai);
            if (isKhach != null)
            {
                return isKhach;
            }
            DB.KhachHangs.Add(khachHang);
            DB.SaveChanges();
            return khachHang;
        }
        public ActionResult Order(FormCollection f)
        {
            KhachHang khachHang;

            if (Session["Cart"] == null)
            {
                return RedirectToAction("ShowCart");
            }
            List<ItemCartViewModel> itemCarts = GetCart();
            if (Session["DangNhap"] != null)
            {
                ThanhVien thanhVien = Session["DangNhap"] as ThanhVien;
                khachHang = DB.KhachHangs.SingleOrDefault(p => p.MaThanhVien == thanhVien.MaThanhVien);
            }
            else
            {
                if (String.IsNullOrEmpty(f["TenKH"]) || String.IsNullOrEmpty(f["DiaChi"]) || String.IsNullOrEmpty(f["DienThoai"]) || String.IsNullOrEmpty(f["Email"]))
                {
                    return Content("Vui lòng điền đủ thông tin !");
                }
                khachHang = new KhachHang();
                khachHang.TenKH = f["TenKH"];
                khachHang.DiaChi = f["DiaChi"];
                khachHang.DienThoai = f["DienThoai"];
                khachHang.Email = f["Email"];
                khachHang = IsKhachHang(khachHang);
            }
           
            DonDatHang donDatHang = new DonDatHang();
            donDatHang.NgayDatHang = DateTime.Now;
            donDatHang.TrinhGiao = false;
            donDatHang.DaThanhToan = false;
            if (khachHang != null)
            {
                donDatHang.MaKH = khachHang.MaKH;
            }
            donDatHang.DaHuy = false;
            DB.DonDatHangs.Add(donDatHang);
            DB.SaveChanges();
            foreach (var itemCart in itemCarts)
            {
                ChiTietDonDatHang chiTiet = new ChiTietDonDatHang();
                chiTiet.MaDDH = donDatHang.MaDDH;
                chiTiet.MaSP = itemCart.MaSP;
                chiTiet.DonGia = itemCart.DonGia;
                chiTiet.SoLuong = itemCart.SoLuong;
                DB.ChiTietDonDatHangs.Add(chiTiet);
            }
            DB.SaveChanges();
            Session["Cart"] = null;
            return Content("<script>window.location.reload()</script>"); 
            //return RedirectToRoute("NotifiCation", new  { noification = "Đặt hàng thành công" });
        }
        public ActionResult NotifiCation(string noification)
        {
            ViewBag.notification = noification;
            return View();
        }
    }
}

WebBanHang/WebBanHang/Areas/Clience/Controllers/ClienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;
using CaptchaMvc.HtmlHelpers;
using CaptchaMvc;
using System.Security.Cryptography;
using System.Text;
using System.Web.UI.WebControls;
using System.Web.ModelBinding;
using System.Web.Security;

namespace WebBanHang.Areas.Clience.Controllers
{
    public class ClienceController : Controller
    {
        // GET: Clience/SanPham
        DBBanHangEntities1 DB= new DatabaseEntity().GetData();
        public ActionResult Home()
        {
            var ListNP = DB.SanPhams.Where(p => p.DaXoa != true && p.Moi == 1 && p.LoaiSanPham.MaLoaiSP == 2).OrderByDescending(p => p.NgayCapNhap).ToList();
            ViewBag.ListNP = ListNP;
            var ListNL = DB.SanPhams.Where(p => p.DaXoa != true && p.Moi == 1 && p.LoaiSanPham.MaLoaiSP == 1).OrderByDescending(p => p.NgayCapNhap).ToList();
            ViewBag.ListNL = ListNL;
            return View();
        }
        [ChildActionOnly]

        public ActionResult ProductStylePatial1()
        {
            
            return View();
        }
        [ChildActionOnly]
        public ActionResult ProductStylePatial2()
        {

            return View();
        }
        public ActionResult MenuPartial()
        {
            var ListProduct = DB.SanPhams;
            return View(ListProduct);
        }
        [HttpGet]
        public ActionResult Register()
        {
            ViewBag.CauHoi = new SelectList(CauHois());
            return View();
        }

        [HttpPost]
        public ActionResult Register(ThanhVien  tv)
        {
            ViewBag.CauHoi = new SelectList(CauHois());
            if (this.IsCaptchaValid("Captcha is Valid"))
            {
                ThanhVien thanhVien = DB.ThanhViens.SingleOrDefault(p=>p.TaiKhoan==tv.TaiKhoan);
                if (thanhVien != null)
                {
                    ViewBag.ThongBao = "Đăng ký Thất bại (Tài khoản đã tồn tại !)";
                    return View();
                }
                thanhVien = DB.ThanhViens.SingleOrDefault(p => p.Email == tv.Email);
                if (thanhVien != null)
                {
                    ViewBag.ThongBao = "Đăng ký Thất bại (Email đã tồn tại !)";
                    return View();
                }
                thanhVien = DB.ThanhViens.SingleOrDefault(p => p.DienThoai == tv.DienThoai);
                if (thanhVien != null)
                {
                    ViewBag.ThongBao = "Đăng ký Thất bại (Số điện thoại đã tồn tại !)";
                    return View();
                }
                if (ModelState.IsValid)
                {
                    ViewBag.ThongBao = "Thêm thành công";
                    tv.MatKhau = GetMD5(tv.MatKhau);
                    DB.ThanhViens.Add(tv);
                    DB.SaveChanges();
                    KhachHang khachHang = new KhachHang();
                    khachHang.DiaChi = tv.DiaChi;
                    khachHang.TenKH = tv.HoTen;
                    khachHang.MaThanhVien = tv.MaThanhVien;
                    khachHang.Email = tv.Email;
                    khachHang.DienThoai = tv.DienThoai;
                    DB.KhachHangs.Add(khachHang);
                    DB.SaveChanges();
                    return RedirectToAction("login", tv);
                }
                else
                {
                    ViewBag.ThongBao = "Đăng ký Thất bại";
                    return View();
                }
                

            }
            ViewBag.ThongBao = "Sai mã captcha";
            return View();
        }

        public List<string> CauHois()
        {
            List<string> cauhois = new List<string>() {"Con vật yêu thích nhất ?"," Các màu sác bạn thích nhất?" };
            return cauhois;
        }
        [HttpPost]
        public ActionResult login(FormCollection f)
        {
            string username = f["username"].ToString();
            string password = GetMD5(f["password"].ToString());
            ThanhVien tv = DB.ThanhViens.SingleOrDefault(p=>p.TaiKhoan==username&&p.MatKhau==password);
            if (tv!=null)
            {
                var listQuyen = DB.LoaiThanhVien_Quyen.Where(p=>p.MaLoaiTV==tv.MaLoaiTV);
                string Quyen = "";
                foreach (var item in listQuyen)
                {
                    Quyen += item.MaQuyen + ",";
                }
                Quyen = Quyen.Substring(0,Quyen.Length-1);
                PhanQuyen(tv.TaiKhoan,Quyen);
                Session["DangNhap"] = tv;
                return Content("<script> window.location.reload(); </script>");
            }
            return Content("Thông tin đăng nhập bị sai .");
        }
        public void PhanQuyen(string TaiKhoan , string Quyen)
        {
            FormsAuthentication.Initialize();
            var ticket = new FormsAuthenticationTicket(
                1,
                TaiKhoan,
                DateTime.Now,
                DateTime.Now.AddHours(3),
                false,
                Quyen,
                FormsAuthentication.FormsCookiePath
                );
            var cookie = new HttpCookie(FormsAuthentication.FormsCookieName,FormsAuthentication.Encrypt(ticket));

            if (ticket.IsPersistent)
            {
                cookie.Expires = ticket.Expiration;
            }
            Response.Cookies.Add(cookie);

        }


        public ActionResult login(int MaThanhVien)
        {
            if (MaThanhVien!=null)
            {
              ThanhVien  thanhVien = DB.ThanhViens.SingleOrDefault(p => p.MaThanhVien == MaThanhVien);
                Session["DangNhap"] = thanhVien;
            }
            return RedirectToAction("Index", "Product");
        }
        public ActionResult KhongDuQuyen()
        {
            return View();
        }
        public ActionResult logout()
        {
            Session["DangNhap"] = null;
            FormsAuthentication.SignOut();
            return RedirectToAction("Home");

        }
        public  string GetMD5(string str)
        {

            MD5CryptoServiceProvider md5 = new MD5CryptoServiceProvider();

            byte[] bHash = md5.ComputeHash(Encoding.UTF8.GetBytes(str));

            StringBuilder sbHash = new StringBuilder();

            foreach (byte b in bHash)
            {

                sbHash.Append(String.Format("{0:x2}", b));

            }

            return sbHash.ToString();

        }        
        public ActionResult PersonalInfor()
        {
            if (Session["DangNhap"] != null && Session["DangNhap"] != "")
            {
                ThanhVien thanhVien = Session["DangNhap"] as ThanhVien;
                return View(thanhVien);
            }
            return RedirectToAction("Home");
        }


    }
}

WebBanHang/WebBanHang/Areas/Clience/Views/Clience/Home.cshtml
@using WebBanHang.Models;
@model IEnumerable<SanPham>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Clience/Views/Shared/_LayoutPage.cshtml";
}
@{
    IEnumerable<SanPham> ListNL = ViewBag.ListNL as IEnumerable<SanPham>;
    IEnumerable<SanPham> ListNP = ViewBag.ListNP as IEnumerable<SanPham>;

}
<div class="container">
    @Html.Partial("ProductStylePatial1", ListNP)
    @Html.Partial("ProductStylePatial2", ListNL)
</div>

<br/><br /><br /><br />

WebBanHang/WebBanHang/Areas/Clience/Views/Clience/KhongDuQuyen.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Quyền không được cấp </title>
</head>
<body>
    <div> 
        <h1 style="color:red">Không đủ quền truy cập</h1>
        <h3>@Html.ActionLink("Trở về","Home","Clience")</h3>
    </div>
</body>
</html>

WebBanHang/WebBanHang/Areas/Clience/Views/Clience/MenuPartial.cshtml
@using WebBanHang.Models;
@model IEnumerable<SanPham>

<div class=" h_menu4">
    <ul class="memenu skyblue">
        <li class="showhide" style="display: list-item;"><span class="title">MENU</span><span class="icon1"></span><span class="icon2"></span></li>
        <li class="active grid" style="display: none;"><a class="color8" href="@Url.Action("Home","Clience")">Trang chủ</a></li>
        @foreach (var gr in Model.Where(p => p.MaLoaiSP != null).GroupBy(p => p.LoaiSanPham))
        {

            <li style="display: none;">
                @if (gr.Key != null)
                {
                    <a class="color1" href="@Url.Action("ShowWithTypeProduct","Product",new { MaLoaiSP =gr.Key.MaLoaiSP})">@gr.Key.TenLoai</a>
                    <div class="mepanel">
                        <div class="row">

                            <div class="col1">
                                <div class="h_nav">
                                    <h4> Nhà cung cấp</h4>
                                    @foreach (var grItem in gr.GroupBy(p => p.NhaCungCap))
                                    {

                                        if (grItem.Key != null)
                                        {

                                            <ul>

                                                @foreach (var item in grItem.GroupBy(p => p.MaNCC))
                                                {
                                                    <li><a href="@Url.Action("ShowWithNCC","Product",new {MaNCC = item.ElementAt(0).MaNCC,MaLoaiSp = gr.Key.MaLoaiSP })">@item.ElementAt(0).NhaCungCap.TenNCC</a></li>
                                                }


                                            </ul>
                                        }

                                    }
                                </div>
                            </div>
                            <div class="col1">
                                <div class="h_nav">
                                    <h4> Nhà sản xuất</h4>
                                    @foreach (var grItem in gr.GroupBy(p => p.NhaSanXuat))
                                    {

                                        if (grItem.Key != null)
                                        {
                                            <ul>
                                                @foreach (var item in grItem.GroupBy(p => p.MaNSX))
                                                {
                                                    <li><a href="@Url.Action("ShowWithNSX","Product",new {MaNSX = item.ElementAt(0).MaNSX,MaLoaiSp = gr.Key.MaLoaiSP })">@item.ElementAt(0).NhaSanXuat.TenNSX</a></li>
                                                }
                                            </ul>
                                        }

                                    }
                                </div>
                            </div>



                        </div>
                    </div>
                }
            </li>
        }
        <li style="display: none;"><a class="color4" href="">Giới thiệu</a></li>
        <li style="display: none;"><a class="color6" href="">Liên hệ</a></li>
        @if (Session["DangNhap"] != null && Session["DangNhap"] != "")
        {
            <li style="display: none;"><a class="color6" href="@Url.Action("PersonalInfor","Clience")">Thông tin cá nhân</a></li>
            <li style="display: none;"><a class="color6" href="@Url.RouteUrl("HomeAdmin")">Admin</a></li>

        }
    </ul>
</div>

WebBanHang/WebBanHang/Areas/Clience/Views/Clience/PersonalInfor.cshtml
@model WebBanHang.Models.ThanhVien

@{
    ViewBag.Title = "PersonalInfor";
    Layout = "~/Areas/Clience/Views/Shared/_ProductLayoutPage.cshtml";
}

<h2>PersonalInfor</h2>

<div>
    <h4>ThanhVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tài khoản
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>

        <dt>
            Mật Khẩu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            Họ và tên 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

        

    </dl>
</div>
@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaThanhVien }) |
</p>*@

WebBanHang/WebBanHang/Areas/Clience/Views/Clience/ProductStylePatial1.cshtml
@using WebBanHang.Models;
@model IEnumerable<SanPham>



<div class="content-top">
    <h1>NEW Phones</h1>
    <div class="grid-in">
        @foreach (var item in Model.Take(3))
        {
            <div class="col-md-4 grid-top">
                <a href="@Url.Action("ProductDetail","Product",new { MaSP = item.MaSP })" class="b-link-stripe b-animate-go  thickbox">
                    <img class="img-responsive" src="@item.HinhAnh" alt="">
                    <div class="b-wrapper">
                        <h3 class="b-animate b-from-left    b-delay03 ">
                            <span>@item.TenSP <br /> </span>
                        </h3>
                    </div>
                </a>


                <p><a href="">Contrary to popular</a></p>
            </div>
        }

        <div class="clearfix"> </div>
    </div>
    
</div>

WebBanHang/WebBanHang/Areas/Clience/Views/Clience/ProductStylePatial2.cshtml
@using WebBanHang.Models;
@model IEnumerable<SanPham>
<style>
  
        .text-font-size-10{
                              font-size:10pt;
                          }
    .text-font-size-6 {
        font-size: 6pt;
    }
    .text-font-size-8 {
        font-size: 8pt;
    }
    
</style>
    <div class="content-top-bottom">
        <h2>New Laptop</h2>
        <div class="col-md-6 men">
            <a href="@Url.Action("ProductDetail","Product",new { MaSP = @Model.ElementAt(0).MaSP })" class="b-link-stripe b-animate-go  thickbox">
                <img class="img-responsive" src="@Model.ElementAt(0).HinhAnh" alt="">
                <div class="b-wrapper">
                    <h3 class="b-animate b-from-top top-in text-font-size-8  b-delay03 ">
                        <span  >@Html.Raw(Model.ElementAt(0).CauHinh)</span>
                    </h3>
                </div>
            </a>


        </div>
        <div class="col-md-6">
            <div class="col-md1 ">
                <a href="@Url.Action("ProductDetail","Product",new { MaSP = @Model.ElementAt(1).MaSP })" class="b-link-stripe b-animate-go  thickbox">
                    <img class="img-responsive" src="@Model.ElementAt(1).HinhAnh" alt="">
                    <div class="b-wrapper">
                        <h3 class="b-animate b-from-top top-in text-font-size-8  b-delay03 ">
                            <span>@Html.Raw(Model.ElementAt(1).CauHinh)</span>
                        </h3>
                    </div>
                </a>

            </div>
            <div class="col-md2">
                <div class="col-md-6 men1">
                    <a href="@Url.Action("ProductDetail","Product",new { MaSP = @Model.ElementAt(2).MaSP })" class="b-link-stripe b-animate-go  thickbox">
                        <img class="img-responsive" src="@Model.ElementAt(2).HinhAnh" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-top top-in  text-font-size-6 b-delay03 ">
                                <span>@Html.Raw(Model.ElementAt(2).CauHinh)</span>
                            </h3>
                        </div>
                    </a>

                </div>
                <div class="col-md-6 men2">
                    <a href="@Url.Action("ProductDetail","Product",new { MaSP = @Model.ElementAt(3).MaSP })" class="b-link-stripe b-animate-go  thickbox">
                        <img class="img-responsive" src="@Model.ElementAt(3).HinhAnh" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-top top-in text-font-size-6  b-delay03 ">
                                <span>@Html.Raw(Model.ElementAt(3).CauHinh)</span>
                            </h3>
                        </div>
                    </a>

                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>